### PR TITLE
Feature/intellijidea 2017.3 compatibility

### LINKED ISSUE #16: Does not install in IntellijIDEA 2017.3.2
1. Open preferences, go to plugins
2. Search "rainbow", click "browse respositories"
3. Click "rainbow"
4. Click "install"
5. Download dialog appears, download completes
6. Plugin is not installed, on closing the settings dialogs there is no prompt to restart

### PR DESCRIPTION
**Pull request by faceleg**
Resolves #16 

- [x] Backward compatibility checking
  - [x] Tested 2016.3.7

### CODE REVIEW

**Comment by zjhmale** [comment]
Cool! It will be super perfect if you can finish the `backward compatibility checking` :)

**Comment by faceleg** [comment]
Down to what versions of intellij?

**Comment by faceleg** [comment]
Works OK for me in:

```
IntelliJ IDEA 2016.3.7
Build #IU-163.15529.5, built on May 19, 2017
Licensed to Lightbox / Michael Robinson
You have a perpetual fallback license for this version
Subscription is active until July 11, 2018
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by zjhmale** [comment]
OK, Cool, IntelliJ 2016 is good enough, thanks :)

**Comment by zjhmale** [comment]
BTW, 2018.1 is not released yet, right?

**Comment by faceleg** [comment]
Thanks @zjhmale !

**Pull request merged**
